### PR TITLE
using the parent-element framework

### PR DESCRIPTION
**Pull request by fchapoton**
Here is a working sketch of making a ring of Hodge diamonds, with HodgeDiamond as element class.

This allow to get rid of some code duplication in addition and multiplication.

All doctests pass, but the TestSuite of the ring still protest.

@tscrim, if you could have a look please ?

### CODE REVIEW

**Comment by tscrim** [comment]
I suspect the `TestSuite` is complaining because the different elements are constructed are not subclasses of (the dynamically created) `HodgeDiamondRing.element_class`.　You can see this in, e.g., `zero()`. Essentially, all of those special constructions should reroute through `HodgeDiamondRing` (which could be a subclass of the stronger `Singleton` class). Similarly the `HodgeDiamondRing` class could take over the constructors such as `from_matrix()`.

**Comment by tscrim** [comment]
Yea, the only thing that will fix that is that all elements that are created are done via `HDR.element_class`. The `Singleton` will just help in making repeated creations/equality/etc. faster.

**Comment by fchapoton** [comment]
Thanks Travis, for your very useful help.

ok, now working, The TestSuite does pass in the console, but not when running with `sage -t` where it complains about pickling, so it is not added to the doctests.

Ready to go, but maybe more doctests should be added for the newly added Parent class ? 

@pbelmans : comments ?

**Comment by tscrim** [comment]
The pickling is likely coming from inheriting from `Element` and not having the proper methods. The question is was that broken before this PR. If not, then we also need to make it work here.

At some point, the actual `HodgeDiamond` class needs a bit of an overhaul since it breaks quite strongly from how everything else in Sage is implemented. In particular, it should behave like an immutable object, take both a matrix and polynomial input and compute the other on demand, and be hashable. (I also strongly dislike Python’s `@property` stuff; especially since most things in Sage are meant to be immutable.) However, that can be done on a later PR.

**Comment by fchapoton** [comment]
But pickling works fine here *in the console*. I think that is an issue with the usage of pickling for classes not in sage main namespace, nothing related to the code here. I have exactly the same issue in some of my private code with other classes.

I agree that some refactoring is in order. I have tried for now not to perturb the existing interface. Let us see if Pieter likes the proposal.

**Comment by tscrim** [comment]
Indeed, but because of `__main__`, things can be a bit different. Well, I would need to try it locally to see and I haven’t done that yet. As you suggested, it isn’t a big deal right now. Indeed, let’s see if Pieter has an opinion.

**Comment by pbelmans** [comment]
Sorry, I am on vacation now, hence the late reply.

I have no immediate comments: if the Sage experts say this is the Sage way, I'm happy to do it like this. Is there something I can do to help at this point? What would be a good example of similar functionality, implemented "the Sage way" to mimic the Hodge diamond cutter on?

**Comment by fchapoton** [comment]
I guess you can merge this one and we will proceed with further re-factoring in later pull requests. This one is not changing the user interface, so should pretty transparent. In my opinion, the changes here are good to go and can be merged safely.

**Comment by pbelmans** [comment]
Thanks a lot!

**Pull request merged**
